version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=facebook/bart-large-cnn
      - PYTHONUNBUFFERED=1
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_TELEGRAM_BOT_URL=${TELEGRAM_BOT_URL:-https://t.me/techaware_bot?start=web}
    depends_on:
      - backend
    restart: unless-stopped
